syntax = "proto3";

enum MessageType {
  kPing = 0;
  kPong = 1;

  // user
  kReqLogin = 2;
  kResLogin = 3;
  kReqLogout = 4;
  kResLogout = 5;
  kReqCreateRoom = 6;
  kResCreateRoom = 7;
  kReqJoinRoom = 8;
  kResJoinRoom = 9;
  kFwdRoom = 10;
  kFwdClient = 12;
  kNtfLeaveRoom = 23;
  kReqLeaveRoom = 24;
  kResLeaveRoom = 25;

  //room
  kUser2RoomReqCreateRoom = 14;
  kUser2RoomResCreateRoom = 15;
  kUser2RoomReqJoinRoom = 16;
  kUser2RoomResJoinRoom = 17;
  kUser2RoomFwdRoom = 18;
  kUser2RoomFwdClient = 20;
  kUser2RoomNtfLeaveRoom = 22;
  kUser2RoomReqLeaveRoom = 26;
  kUser2RoomResLeaveRoom = 27;

  reserved 11, 13, 19, 21;
}
