syntax = "proto3";

message ReqCreateRoom {
  uint64 request_id = 1;
}

message ResCreateRoom {
  uint64 request_id = 1;
  bool success = 2;
  uint32 room_id = 3;
}

message ReqJoinRoom {
  uint64 request_id = 1;
  uint32 room_id = 3;
}

message ResJoinRoom {
  uint64 request_id = 1;
  bool success = 2;
  uint32 room_id = 3;
}

message FwdRoom {
  reserved 1;
  string message = 2;
  // repeated string users = 3;
}

message ReqLeaveRoom {
  uint64 request_id = 1;
}

message ResLeaveRoom {
  uint64 request_id = 1;
  bool success = 2;
}
